name: air-quality-daily

on:
  workflow_dispatch:
    #schedule:
    #- cron: '11 6 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    env:
      HOPSWORKS_API_KEY: WHEGzZQDlW94iLTy.AdD83z6aTRlRAEgHRLPflZi5XuzfydfZYHKc9zD1mHopQQyrqKHOMOUZN2qJxLW0
      AQICN_API_KEY:    09210bb7f0477fdc41b6471eea0d6563ce6d0b16
      AQICN_COUNTRY:    sweden
      AQICN_CITY:       stockholm
      AQICN_STREET:     hornsgatan-108
      AQICN_URL:        https://api.waqi.info/feed/@10009


    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Create .env for notebooks
        working-directory: ${{ github.workspace }}
        run: |
          cat > .env <<'EOF'
          HOPSWORKS_API_KEY=WHEGzZQDlW94iLTy.AdD83z6aTRlRAEgHRLPflZi5XuzfydfZYHKc9zD1mHopQQyrqKHOMOUZN2qJxLW0
          AQICN_API_KEY=09210bb7f0477fdc41b6471eea0d6563ce6d0b16
          AQICN_COUNTRY=sweden
          AQICN_CITY=stockholm
          AQICN_STREET=hornsgatan-108
          AQICN_URL=https://api.waqi.info/feed/@10009
          EOF

      - name: install python packages
        run: |
          cd .
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          cd notebooks/airquality
          jupyter nbconvert --to notebook --execute 2_air_quality_feature_pipeline.ipynb
          jupyter nbconvert --to notebook --execute 4_air_quality_batch_inference.ipynb

      - name: github pages publish
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Air Quality Dashboard published"
          commit_options: '--no-verify --signoff'

          file_pattern: 'docs/air-quality/assets/img/* docs/_includes/*'

          repository: .

          status_options: '--untracked-files=no'

          skip_dirty_check: true

          skip_fetch: true

          skip_checkout: true

          push_options: '--force'
